config/routes.rb
Rails.application.routes.draw do
  resources :votes
  resources :links
  resources :study_groups

  root 'study_groups#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  # relationship - link consists of many votes - composition in class diagram
  has_many :votes

  # relationship - every link belongs to a certain study group - aggregation in class diagram
  belongs_to :study_group
end

app/models/study_group.rb
class StudyGroup < ApplicationRecord
  # relationship - one study group can have multiple links - aggregation in class diagram
  has_many :links
end

app/models/vote.rb
class Vote < ApplicationRecord
  # relationship - link consists of multiple votes - composition
  belongs_to :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]


  # Display_all_links_within_study_group()

  # fetches all links with counts of their votes within a selected study groups
  # therefore it also implements Count_votes_of_link() method
  def self.get_links(study_group_id, params)
    @link = Link.select("links.id, links.title, links.url, links.description, COALESCE(SUM(votes.value), 0) as vote_sum")
                .left_outer_joins(:votes)
                .where(study_group_id: study_group_id).group("links.id").order("vote_sum DESC")
                .paginate(:page => params[:page], :per_page => 6)
  end


  # search_links()
  def search_links(query)
    @link = Link.find_by(title: query)
  end


  # creates new link allowing user to input its attributes
  def new
    @study_group_id = params[:group_id]
    @link = Link.new
  end


  # Create_new_link()
  # Creates and stores new link
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        group = StudyGroup.find(@link.study_group_id)
        format.html { redirect_to group }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end


  # Delete_link()
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    def set_link
      @link = Link.find(params[:id])
    end

    def link_params
      params.require(:link).permit(:title, :url, :description, :study_group_id, :keywords)
    end
end

app/controllers/study_groups_controller.rb
class StudyGroupsController < ApplicationController
  before_action :set_study_group, only: [:show, :edit, :update, :destroy]

  # Find student's course groups()
  # returns all groups that student that is logged inhas joined
  def index
    @study_groups = StudyGroup.all
  end


  # Display course group()
  # displays selected course group and all links within
  def show
    @links = LinksController.get_links(@study_group.id, params)
    @vote = Vote.new
  end


  def new
    @study_group = StudyGroup.new
  end


  def edit
  end

  # Create a new group()
  # creates new group
  def create
    @study_group = StudyGroup.new(study_group_params)

    respond_to do |format|
      if @study_group.save
        format.html { redirect_to @study_group, notice: 'Study group was successfully created.' }
        format.json { render :show, status: :created, location: @study_group }
      else
        format.html { render :new }
        format.json { render json: @study_group.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @study_group.update(study_group_params)
        format.html { redirect_to @study_group, notice: 'Study group was successfully updated.' }
        format.json { render :show, status: :ok, location: @study_group }
      else
        format.html { render :edit }
        format.json { render json: @study_group.errors, status: :unprocessable_entity }
      end
    end
  end


  # delete_group()
  def destroy
    @study_group.destroy
    respond_to do |format|
      format.html { redirect_to study_groups_url, notice: 'Study group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_study_group
      @study_group = StudyGroup.find(params[:id])
    end

    def study_group_params
      params.require(:study_group).permit(:name)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]


  def index
    @votes = Vote.all
  end


  def show
  end

  def new
    @vote = Vote.new
  end


  def edit
  end


  # Submit_vote() and also calls vote verification
  def create
    @vote = Vote.new(vote_params)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to request.referer}
      else
        format.html { render :new }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url, notice: 'Vote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_vote
      @vote = Vote.find(params[:id])
    end

    def vote_params
      params.require(:vote).permit(:value, :link_id, :student_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/study_groups_helper.rb
module StudyGroupsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Linkalot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="flex_col">
      <%= yield %>
    </div>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_for(link) do |f| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

    <%= f.hidden_field :study_group_id , value: @study_group_id %>

  <div class="field">
    <%= f.label :keywords %>
    <%= f.text_field :keywords %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Links</h1>

<table>
  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.title %></td>
        <td><%= link.url %></td>
        <td><%= link.description %></td>
        <td><%= link.study_group_id %></td>
        <td><%= link.keywords %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<!-- generates form -->
<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @link.description %>
</p>

<p>
  <strong>Studygroup:</strong>
  <%= @link.study_group_id %>
</p>

<p>
  <strong>Keywords:</strong>
  <%= @link.keywords %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/study_groups/_form.html.erb
<%= form_for(study_group) do |f| %>
  <% if study_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(study_group.errors.count, "error") %> prohibited this study_group from being saved:</h2>

      <ul>
      <% study_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/study_groups/edit.html.erb
<h1>Editing Study Group</h1>

<%= render 'form', study_group: @study_group %>

<%= link_to 'Show', @study_group %> |
<%= link_to 'Back', study_groups_path %>

app/views/study_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome, Mr. Khail!</h1>

Here are all course groups that you have joined:
<br />
<br />

<table>
  <tbody>
    <% @study_groups.each do |study_group| %>
      <tr>
        <td><%= link_to study_group.name, study_group %></td>
        <td><%= link_to 'Leave', study_group, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/study_groups/new.html.erb
<h1>New Study Group</h1>

<%= render 'form', study_group: @study_group %>

<%= link_to 'Back', study_groups_path %>

app/views/study_groups/show.html.erb
<div class="header flex_col">
  <%= @study_group.name %>
</div>


<div class="flex_col">

  <div class="flex_col add_new_box">
    <%= link_to 'Add new link', new_link_path(:group_id => @study_group.id) %>
  </div>

  <div class="links_box">
    <div class="links_rows">
      <% @links.each do |link| %>
          <div class="links_cols flex_col">

            <div class="link_header"><a href="<%= link.url %>"><%= link.title %></a></div>

            <!-- Fetch link miniature from the Internet -->
            <% thumb = Grabbit.url(link.url) %>

            <div class="thumb_box"><a class="image_link" href="<%= link.url %>">
              <img src="<%= thumb.images.first %>" class="link_thumbnail" /></a>
            </div>

            <div class="link_description"><%= link.description %></div>

            <div class="vote_buttons">
              <div class="vote_item">
                <div class="votes_num"><%= link.vote_sum %></div>
                <%= render partial: 'votes/form', locals: {vote: @vote, vote_value: 1, link_id: link.id} %>
                <%= render partial: 'votes/form',  locals: {vote: @vote, vote_value: -1, link_id: link.id} %>
              </div>
            </div>

          </div>
      <% end %>
    </div>
  </div>

  <%= will_paginate @links %>

</div>

<%= link_to 'Back', study_groups_path %>

app/views/votes/_form.html.erb
<%= form_for(vote) do |f| %>
  <% if vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.hidden_field :value, value: vote_value %>
    <%= f.hidden_field :link_id, value: link_id %>
    <%= f.hidden_field :ip_address, value: request.remote_ip %>


    <% if vote_value > 0 %>
      <%= f.submit "Upvote", :type => :image, :src => image_path('Like.png'), :class => 'vote_img' %>
    <% else %>
      <%= f.submit "Downvote", :type => :image, :src => image_path('Disike.png'), :class => 'vote_img' %>
    <% end %>

<% end %>

app/views/votes/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Votes</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Link</th>
      <th>Ip address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.value %></td>
        <td><%= vote.link_id %></td>
        <td><%= vote.ip_address %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @vote.value %>
</p>

<p>
  <strong>Link:</strong>
  <%= @vote.link_id %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @vote.ip_address %>
</p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>